"""Added Combo and Favourite tables

Revision ID: bf3e0220eef2
Revises: 9fc440c85985
Create Date: 2024-09-03 19:54:56.473802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3e0220eef2'
down_revision = '9fc440c85985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Combo',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('notation', sa.String(), nullable=False),
    sa.Column('drive', sa.String(), nullable=False),
    sa.Column('bars', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('notation')
    )
    op.create_table('Favourite',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['Combo.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favourite')
    op.drop_table('Combo')
    # ### end Alembic commands ###
